### ISSUE TITLE
Signature List is malformed

### ISSUE THREAD

**Issue by gleidson** [rhinstaller/dbxtool#2]
The dbxtool service fail to start with the message "EFI Signature List is malformed"

----

```
$ systemctl status dbxtool 

● dbxtool.service - Secure Boot DBX (blacklist) updater
   Loaded: loaded (/usr/lib/systemd/system/dbxtool.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-11-01 10:46:53 -02; 5h 11min ago
  Process: 1276 ExecStart=/usr/bin/dbxtool -a /usr/share/dbxtool/ -q (code=exited, status=1/FAILURE)
 Main PID: 1276 (code=exited, status=1/FAILURE)

Nov 01 10:46:53 inspiron7000 dbxtool[1276]: dbxtool: EFI Signature List is malformed
Nov 01 10:46:53 inspiron7000 dbxtool[1276]: dbxtool: list has 2343 bytes left, element is 1691 bytes
Nov 01 10:46:52 inspiron7000 systemd[1]: Started Secure Boot DBX (blacklist) updater.
Nov 01 10:46:53 inspiron7000 systemd[1]: dbxtool.service: Main process exited, code=exited, status=1/FAILURE
Nov 01 10:46:53 inspiron7000 systemd[1]: dbxtool.service: Unit entered failed state.
Nov 01 10:46:53 inspiron7000 systemd[1]: dbxtool.service: Failed with result 'exit-code'.
```
-----
System information
Fedora 27
Package version: dbxtool-8-3.fc27.x86_64

@vathpela , if you need more information, let me know. 
RH_Bugzilla: 1489942

**Comment by neingeist** [comment]
This is fixed for me in 338a2d09 (current HEAD).

**Comment by t3kk** [comment]
This bug still existing on the 8 tag but is fixed in the master branch. Any chance it might make it into a release soon? I've managed to get my dbx updated just by building this for myself, but with a new dbx update posted 10 days ago there may be others attempting an update like myself.

I'm super glad this tool exists. Thank you for your work!

**Comment by frozencemetery** [comment]
Thanks for your interest in dbxtool.  dbxtool has been obsoleted by [fwupd](https://github.com/fwupd/fwupd); we recommend using that instead and will shortly be archiving this repository.
