### ISSUE TITLE
Could not apply database update "DBXUpdate-2016-08-09-13-16-00.bin"

### ISSUE THREAD

**Issue by cmurf** [rhinstaller/dbxtool#3]
This is the same as https://bugzilla.redhat.com/show_bug.cgi?id=1516599#c4

It happens on an Intel NUC
 [    0.000000] DMI:                  /NUC5PPYB, BIOS PYBSWCEL.86A.0063.2017.0807.1503 08/07/2017

with
```
# rpm -q dbxtool
dbxtool-8-3.fc27.x86_64
```

[vars.tar.gz](https://github.com/rhboot/dbxtool/files/1504555/vars.tar.gz)

**Comment by neingeist** [comment]
Workaround: `chattr -i /sys/firmware/efi/efivars/dbx-*`. Maybe this is already fixed here in git.

**Comment by frozencemetery** [comment]
Thanks for your interest in dbxtool.  dbxtool has been obsoleted by [fwupd](https://github.com/fwupd/fwupd); we recommend using that instead and will shortly be archiving this repository.
